/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CampOrganizerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.HealthCampOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MedicalFieldCampWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author piyush
 */
public class MedicalFieldCampWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LegalWorkRequestJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    Network network;
    UserAccount userAccount;
    private HealthCampOrganization HealthCampOrganization;

    public MedicalFieldCampWorkRequestJPanel(JPanel userProcessContainer, EcoSystem business, Network network, UserAccount userAccount, HealthCampOrganization HealthCampOrganization) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.system = business;
        this.network = network;
        this.userAccount = userAccount;
        this.HealthCampOrganization = HealthCampOrganization;

        populateFields();
    }

    private void populateFields() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtComments = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCampName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCampVenue = new javax.swing.JTextField();
        jDateStartDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDateEndDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(4, 65, 96));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 63, 65));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Field Camp Work Request");
        add(jLabel1);
        jLabel1.setBounds(0, 20, 880, 33);
        add(txtComments);
        txtComments.setBounds(325, 300, 187, 35);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(4, 65, 96));
        jLabel4.setText("Comments:");
        add(jLabel4);
        jLabel4.setBounds(183, 306, 114, 23);

        btnSubmit.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(60, 63, 65));
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(385, 360, 127, 33);

        btnHome.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(60, 63, 65));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        add(btnHome);
        btnHome.setBounds(6, 61, 108, 33);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(4, 65, 96));
        jLabel5.setText("Camp Name:");
        add(jLabel5);
        jLabel5.setBounds(169, 126, 128, 23);
        add(txtCampName);
        txtCampName.setBounds(325, 120, 187, 35);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(4, 65, 96));
        jLabel6.setText("Camp Venue:");
        add(jLabel6);
        jLabel6.setBounds(163, 165, 134, 23);
        add(txtCampVenue);
        txtCampVenue.setBounds(325, 165, 187, 35);
        add(jDateStartDate);
        jDateStartDate.setBounds(325, 210, 187, 35);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(4, 65, 96));
        jLabel7.setText("Start Date:");
        add(jLabel7);
        jLabel7.setBounds(187, 212, 110, 23);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(4, 65, 96));
        jLabel8.setText("End Date:");
        add(jLabel8);
        jLabel8.setBounds(199, 267, 98, 23);
        add(jDateEndDate);
        jDateEndDate.setBounds(325, 255, 187, 35);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(60, 63, 65));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/CampOrganizerRole/cam.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(240, 270, 640, 390);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        Organization org = null;
        for (Network eachnetwork : system.getNetworkList()) {
            if (eachnetwork == network) {
                for (Enterprise enterprise : eachnetwork.getEnterpriseDirectory().getEnterpriseList()) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof DoctorOrganization) {
                            org = organization;
                            break;
                        }
                    }
                }
            }
        }

        if (org != null) {
            MedicalFieldCampWorkRequest fieldCampwf = new MedicalFieldCampWorkRequest();
            try {
                fieldCampwf.setWorkID(org.getWorkQueue().getWorkRequestList().get(org.getWorkQueue().getWorkRequestList().size() - 1).getWorkID() + 1);
            } catch (Exception e) {
                fieldCampwf.setWorkID(601);
            }
            fieldCampwf.setFieldCampName(txtCampName.getText());
            fieldCampwf.setVenue(txtCampVenue.getText());
            fieldCampwf.setStartDate(jDateStartDate.getDate());
            fieldCampwf.setEndDate(jDateEndDate.getDate());
            fieldCampwf.setMessage(txtComments.getText());
            fieldCampwf.setSender(userAccount);
            fieldCampwf.setStatus("New Request");
            org.getWorkQueue().getWorkRequestList().add(fieldCampwf);
//            JOptionPane.showMessageDialog(null,"Report has been generated");
            JOptionPane.showMessageDialog(null, "Request '" + fieldCampwf.getWorkID() + "' Raised Succesfully !");
//            userAccount.getWorkQueue().getWorkRequestList().add(fieldCampwf);
            btnHomeActionPerformed(evt);

        }


    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CampOrganizerRoleJPanel dwjp = (CampOrganizerRoleJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);


    }//GEN-LAST:event_btnHomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSubmit;
    private com.toedter.calendar.JDateChooser jDateEndDate;
    private com.toedter.calendar.JDateChooser jDateStartDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCampName;
    private javax.swing.JTextField txtCampVenue;
    private javax.swing.JTextField txtComments;
    // End of variables declaration//GEN-END:variables
}
