/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LegalAdvisorRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.LegalOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LegalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author piyush
 */
public class LegalAdvisorRoleJPanel extends javax.swing.JPanel {

//    JPanel userProcessContainer, UserAccount account, Organization organization, 
//    Enterprise enterprise, EcoSystem business,Network network
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private LegalOrganization LegalOrganization;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private EcoSystem system;
    private Network network;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    /**
     * Creates new form LegalAdvisorRoleJPanel
     */
    public LegalAdvisorRoleJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.LegalOrganization = (LegalOrganization) organization;
//        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.network = network;
        system = dB4OUtil.retrieveSystem();

        // User function
        populateTable();
    }
    


    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) LegalPaperJTable.getModel();
        model.setRowCount(0);
        for (WorkRequest request : LegalOrganization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[9];
            row[0] = request;
            row[1] = request.getRequestDate();
            row[2] = request.getStatus();
            row[3] = request.getReceiver();
            row[4] = request.getMessage();
            
            row[5] = ((LegalWorkRequest) request).getPatient_name();
            row[6] = ((LegalWorkRequest) request).getDonor().getName();
            row[7] = ((LegalWorkRequest) request).getDonor().getContactNum();
            
            int i = 0;
            try {
            if(((LegalWorkRequest) request).getServiceOne())
                i++;
            if(((LegalWorkRequest) request).getServiceTwo())
                i++;
            }
            catch (Exception e) {
                
            }
            row[8] = i;
            
            model.addRow(row);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpService = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LegalPaperJTable = new javax.swing.JTable();
        btnHome = new javax.swing.JButton();
        btnAssignToSelf = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnProcess = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Legal Advisor");

        LegalPaperJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "WorkID", "Start Date", "Status", "Ownership", "Message", "Patient Name", "Donor Name", "Contact", "Services"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(LegalPaperJTable);

        btnHome.setText("HOME");
        btnHome.setEnabled(false);

        btnAssignToSelf.setText("Assign To Self");
        btnAssignToSelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToSelfActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnHome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRefresh))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnAssignToSelf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHome)
                    .addComponent(btnRefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignToSelf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignToSelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToSelfActionPerformed
        // TODO add your handling code here:
        int selectedRow = LegalPaperJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "No Row Selected, Please select one");
            return;
        }
        WorkRequest request = (WorkRequest) LegalPaperJTable.getValueAt(selectedRow, 0);
        
        if (request.getStatus().equalsIgnoreCase("New Request")) {
            for (WorkRequest requestCheck : LegalOrganization.getWorkQueue().getWorkRequestList()) {
                
                if(requestCheck.getReceiver() != null && requestCheck.getReceiver().equals(userAccount) && (requestCheck.getStatus().equalsIgnoreCase("Assigned") || requestCheck.getStatus().equalsIgnoreCase("Work In Progress"))){
                    JOptionPane.showMessageDialog(null, "User already working on a work request");
                    return;
                }
            }
            request.setReceiver(userAccount);
            request.setStatus("Assigned");
            populateTable();
        } else {
            JOptionPane.showMessageDialog(null, "This request is already being handled");
        }
        populateTable();
    }//GEN-LAST:event_btnAssignToSelfActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int selectedRow = LegalPaperJTable.getSelectedRow();
        if (selectedRow < 0) {
           JOptionPane.showMessageDialog(null, "No Row Selected, Please select one");
           return;
        }
        
        LegalWorkRequest request = (LegalWorkRequest) LegalPaperJTable.getValueAt(selectedRow, 0);
        
        UserAccount requestuserAccount = request.getReceiver();
        if(requestuserAccount == null){
            JOptionPane.showMessageDialog(null, "Request not assigned to you");
            return;
        }
        if (requestuserAccount.equals(userAccount)){
        LegalWorkRequestJPanel LegalWorkRequestJPanel = new LegalWorkRequestJPanel(userProcessContainer, request, business, network, userAccount);
        userProcessContainer.add("processWorkRequestJPanel", LegalWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else {
            JOptionPane.showMessageDialog(null, "Request not assigned to you");
        }
        
        
    }//GEN-LAST:event_btnProcessActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LegalPaperJTable;
    private javax.swing.JButton btnAssignToSelf;
    private javax.swing.ButtonGroup btnGrpService;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
