/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CounselorRole;

import Business.EcoSystem;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EmotionalWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.Date;

/**
 *
 * @author piyush
 */
public class CounselorWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LegalWorkRequestJPanel
     */
    
    JPanel userProcessContainer;
    EmotionalWorkRequest request;
    EcoSystem system;
    Network network;
    UserAccount userAccount;
    
    public CounselorWorkRequestJPanel(JPanel userProcessContainer, EmotionalWorkRequest request, EcoSystem business, Network network, UserAccount userAccount) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.system = business;
        this.network = network;
        this.userAccount = userAccount;
        
        populateFields();
    }

    private void populateFields(){
        
        
        if(request.getStatus().equalsIgnoreCase("Assigned")){
            jCheckBox1.setEnabled(true);
            jCheckBox2.setEnabled(true);
            jCheckBox3.setEnabled(true);
            jCheckBox4.setEnabled(true);
        } else {
            jCheckBox1.setSelected(request.getServiceOne());
            jCheckBox2.setSelected(request.getServiceTwo());
            jCheckBox3.setSelected(request.getServiceThree());
            jCheckBox4.setSelected(request.getServiceFour());
            jCheckBox1.setEnabled(false);
            jCheckBox2.setEnabled(false);
            jCheckBox3.setEnabled(false);
            jCheckBox4.setEnabled(false);
        }
        if(request.getStatus().equalsIgnoreCase("Complete")){
            btnSubmit.setEnabled(false);
            ChangeStatusdd.setEnabled(false);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtComments = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        ChangeStatusdd = new javax.swing.JComboBox<>();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 65, 96));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Counselor Work Request");
        add(jLabel1);
        jLabel1.setBounds(6, 16, 890, 33);

        jCheckBox1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("1. Behavioural Therapy");
        add(jCheckBox1);
        jCheckBox1.setBounds(104, 182, 340, 22);
        add(txtComments);
        txtComments.setBounds(104, 470, 200, 30);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Comments");
        add(jLabel4);
        jLabel4.setBounds(104, 445, 250, 18);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Work Request Status Updates");
        add(jLabel3);
        jLabel3.setBounds(104, 349, 260, 18);

        btnSubmit.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(4, 65, 96));
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(326, 470, 130, 29);

        ChangeStatusdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Work in Progress", "Complete" }));
        ChangeStatusdd.setSelectedIndex(-1);
        ChangeStatusdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeStatusddActionPerformed(evt);
            }
        });
        add(ChangeStatusdd);
        ChangeStatusdd.setBounds(104, 374, 170, 30);

        jCheckBox2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox2.setText("2. Emotionally Focused Therapy");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        add(jCheckBox2);
        jCheckBox2.setBounds(104, 219, 340, 22);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Legal Service Opted:");
        add(jLabel2);
        jLabel2.setBounds(104, 157, 200, 18);

        btnHome.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(4, 65, 96));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        add(btnHome);
        btnHome.setBounds(6, 61, 130, 29);

        jCheckBox3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox3.setText("4. Emotionally Focused Therapy");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        add(jCheckBox3);
        jCheckBox3.setBounds(100, 290, 340, 22);

        jCheckBox4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox4.setText("3. Behavioural therapy");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        add(jCheckBox4);
        jCheckBox4.setBounds(104, 256, 340, 21);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/CounselorRole/CWR.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(360, 60, 900, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String selectedStatus = ChangeStatusdd.getSelectedItem().toString();
        if (selectedStatus.equalsIgnoreCase("None")){
            JOptionPane.showMessageDialog(null, "Please select Work Status");
            return;
        }
        if(request.getStatus().equalsIgnoreCase("Assigned")){
            
//            if (!selectedStatus.equalsIgnoreCase("None")){
            request.setServiceOne(jCheckBox1.isSelected());
            request.setServiceTwo(jCheckBox2.isSelected());
            request.setServiceThree(jCheckBox3.isSelected());
            request.setServiceFour(jCheckBox4.isSelected());
            request.setStatus(selectedStatus);
            if (selectedStatus.equalsIgnoreCase("Complete")){
                request.setResolveDate(new Date());
            }
            request.setMessage(txtComments.getText());
            btnHomeActionPerformed(evt);
//            }
            
        } else {
            if (!selectedStatus.equalsIgnoreCase(request.getStatus())){
            request.setStatus(selectedStatus);
            if (selectedStatus.equalsIgnoreCase("Complete")){
                request.setResolveDate(new Date());
            }
            request.setMessage(txtComments.getText());
            btnHomeActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(null, "Work Status is same as current");
            }
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void ChangeStatusddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeStatusddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeStatusddActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CounselorRoleJPanel dwjp = (CounselorRoleJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
    }//GEN-LAST:event_btnHomeActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ChangeStatusdd;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtComments;
    // End of variables declaration//GEN-END:variables
}
