/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DonorRole;


import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
//import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.Person.DonorDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author saksh
 */
public class DonorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    DB4OUtil dB4OUtil;
//    private DonorOrganization organization;
//    private Enterprise enterprise;
//    private UserAccount userAccount;
//    private EnterpriseDirectory enterpriseDirectory;
    private EcoSystem ecosystem;
    private DonorDirectory donorDirectory;
   // private DonorOrganization organization;
    
    /**
     * Creates new form DonorWorkAreaJPanel
     */
    public DonorWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system, DonorDirectory donorDirectory, DB4OUtil dB4OUtil) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        //this.organization = organization;
//        this.enterprise = enterprise;
        this.ecosystem = system;
        this.dB4OUtil = dB4OUtil;
        this.donorDirectory = donorDirectory;
        populateCityComboBox();
//        this.userAccount = account;
//        this.enterpriseDirectory = new EnterpriseDirectory();
        
        
    }
    
    public void populateCityComboBox(){
        cityJComboBox.removeAllItems();
        
        for (Network network : ecosystem.getNetworkList()){
            cityJComboBox.addItem(network);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        radYes = new javax.swing.JRadioButton();
        radNo = new javax.swing.JRadioButton();
        cityJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 65, 96));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Donor Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 869, 40));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("City:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        btnSubmit.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(4, 65, 96));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 160, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Interested in organ donation:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        buttonGroup1.add(radYes);
        radYes.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        radYes.setForeground(new java.awt.Color(0, 51, 51));
        radYes.setText("Yes");
        add(radYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 79, -1));

        buttonGroup1.add(radNo);
        radNo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        radNo.setForeground(new java.awt.Color(0, 51, 51));
        radNo.setText("No");
        add(radNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 67, -1));

        cityJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Boston", "New York" }));
        cityJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityJComboBoxActionPerformed(evt);
            }
        });
        add(cityJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 160, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(4, 65, 96));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/DonorRole/dR.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 869, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        String city = cityJComboBox.getSelectedItem().toString();
        
        if(radYes.isSelected()){
            JOptionPane.showMessageDialog(null, "Please fill up the donor registration form");
            DonorRegistrationFormJPanel don = new DonorRegistrationFormJPanel(userProcessContainer, ecosystem, city, donorDirectory,dB4OUtil);
            userProcessContainer.add("DonorRegistrationFormJPanel",don);         
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void cityJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityJComboBoxActionPerformed
       
    }//GEN-LAST:event_cityJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cityJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton radNo;
    private javax.swing.JRadioButton radYes;
    // End of variables declaration//GEN-END:variables
}
