/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DonorRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.EmployeeDirectory;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
//import Business.Organization.DonorOrganization;
import Business.Organization.OrganTissueDonationOrganization;
import Business.Organization.Organization;
import Business.Person.Donor;
import Business.Person.DonorDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author saksh
 */
public class DonorRegistrationFormJPanel extends javax.swing.JPanel {
       // Organization organization;
        JPanel userProcessContainer;
        String emailAdd;
        EcoSystem ecosystem;
        String city;
        DB4OUtil dB4OUtil;
        //DonorOrganization organization;
        DonorDirectory donorDirectory;
         List<String> userList = new ArrayList<String>();
//        EmployeeDirectory employeeD;
//        
    /**
     * Creates new form DonorRegistrationFormJPanel
     */
    List<String> organList = new ArrayList<String>();
    
    public DonorRegistrationFormJPanel(JPanel userProcessContainer, EcoSystem system, String city, DonorDirectory donorDirectory,DB4OUtil dB4OUtil) {
        initComponents();
        //this.organization = organization;
        this.userProcessContainer = userProcessContainer;
       // this.emailAdd=email;
        //txtEmailId.setText(email);
        //txtContactDonor.setText();
        txtCity.setText(city);
        txtCity.setEnabled(false);
        this.ecosystem = system;
        this.city = city;
        this.donorDirectory = donorDirectory;
        this.dB4OUtil =dB4OUtil;
        popuser();
//        this.employeeD = new EmployeeDirectory();
//        System.out.println("Donor Direcotry"+donorDirectory.getDonorList());
//                System.out.println("Emp Direcotry"+employeeD.getEmployeeList());
    }
    public void popuser(){
        for(Donor d:ecosystem.getDonorDirectory()){
            userList.add(d.getName());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtContactDonor = new javax.swing.JTextField();
        txtEmailId = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtEmergencyName = new javax.swing.JTextField();
        txtEmergencyContact = new javax.swing.JTextField();
        txtSignature = new javax.swing.JTextField();
        radMale = new javax.swing.JRadioButton();
        radFemale = new javax.swing.JRadioButton();
        radOrganAvailYes = new javax.swing.JRadioButton();
        radOrganAvailNo = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        organJComboBox = new javax.swing.JComboBox();
        lblOrgan1 = new javax.swing.JLabel();
        bloodGroupJComboBox1 = new javax.swing.JComboBox();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        btnRegister1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 65, 96));
        jLabel1.setText("Donor Registration Form");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Full Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Age:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Sex:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Blood Group:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Contact Number:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Email-Id:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Address:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Organ to donate:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Is organ available now:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText("Point of contact in emergency:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 310, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 51));
        jLabel12.setText("Name:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("Digital Sig:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, 120, 30));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setText("Contact number:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 144, -1));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 144, -1));
        add(txtContactDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 144, -1));
        add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 144, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 144, -1));
        add(txtEmergencyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 170, -1));

        txtEmergencyContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmergencyContactActionPerformed(evt);
            }
        });
        add(txtEmergencyContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 170, -1));

        txtSignature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignatureActionPerformed(evt);
            }
        });
        add(txtSignature, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, 210, 23));

        buttonGroup1.add(radMale);
        radMale.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        radMale.setForeground(new java.awt.Color(0, 51, 51));
        radMale.setText("Male");
        add(radMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 90, -1));

        buttonGroup1.add(radFemale);
        radFemale.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        radFemale.setForeground(new java.awt.Color(0, 51, 51));
        radFemale.setText("Female");
        add(radFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 100, -1));

        radOrganAvailYes.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        radOrganAvailYes.setForeground(new java.awt.Color(0, 51, 51));
        radOrganAvailYes.setText("Yes");
        add(radOrganAvailYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 80, -1));

        radOrganAvailNo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        radOrganAvailNo.setForeground(new java.awt.Color(0, 51, 51));
        radOrganAvailNo.setText("No");
        add(radOrganAvailNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 60, -1));

        btnBack.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(4, 65, 96));
        btnBack.setText("HOME");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 40));

        organJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Heart", "Lungs", "Kidneys", "Liver", "Small Bowel", "Pancreas" }));
        organJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organJComboBoxActionPerformed(evt);
            }
        });
        add(organJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 146, -1));
        add(lblOrgan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 387, 266, 22));

        bloodGroupJComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "B Positive", "B Negative", "A Positive", "A Negative", "O Positive", "O Negative" }));
        bloodGroupJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupJComboBox1ActionPerformed(evt);
            }
        });
        add(bloodGroupJComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 150, -1));

        lblCity.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblCity.setForeground(new java.awt.Color(0, 51, 51));
        lblCity.setText("City:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 170, -1));

        btnRegister1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnRegister1.setForeground(new java.awt.Color(4, 65, 96));
        btnRegister1.setText("Register");
        btnRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegister1ActionPerformed(evt);
            }
        });
        add(btnRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 610, 120, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(4, 65, 96));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/DonorRole/reg.png"))); // NOI18N
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 970, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEmergencyContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmergencyContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmergencyContactActionPerformed

    private void txtSignatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSignatureActionPerformed

    private void organJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organJComboBoxActionPerformed
//            JLabel newLabel = new JLabel();
//            //labels.add(newLabel);
//            newLabel.setBounds(0, 0, 200, 200);
//            newLabel.setText("hello");
//            add(newLabel);
            
            //validate();
            organList.add((String) organJComboBox.getSelectedItem());
            if(lblOrgan1.getText()==""){
                lblOrgan1.setText((String) organJComboBox.getSelectedItem());
            }
            else{
            lblOrgan1.setText(lblOrgan1.getText() + ", " +(String) organJComboBox.getSelectedItem());
            }
    }//GEN-LAST:event_organJComboBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //organization.getEmployeeDirectory().createEmployee(name);
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void bloodGroupJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupJComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGroupJComboBox1ActionPerformed
 public boolean isFirstnameValid(String text) {

        if(text.matches("^([A-Za-z]+)(\\s[A-Za-z]+)*\\s?$")){
            for(String s:userList){
                if(s.equalsIgnoreCase(text)){
                    JOptionPane.showMessageDialog(null, "User already exists");
                    return false;
                }
            }
            
            return true;
        }
        else{
            JOptionPane.showMessageDialog(null, "Names should contain only alphabets");
            return false;
        }
    }
   private boolean valage(String age){
       Pattern pattern = Pattern.compile("[0-9]+");
       Matcher matcher = pattern.matcher(age);
        boolean bool = matcher.matches();
        if (!bool) {
            JOptionPane.showMessageDialog(null,"Age should only be numbers");
            return false;
        } else {
           int age1 = Integer.parseInt(age);
           if(age1<0 || age1>200){
                JOptionPane.showMessageDialog(null,"Age should between");
           }
            return true;
        }
     }
       private boolean valPhone(String ph){
      Pattern pattern = Pattern.compile("[0-9]{10}");
        Matcher matcher = pattern.matcher(ph);
        boolean bool = matcher.matches();
        if (!bool) {
            return true;
            //JOptionPane.showMessageDialog(null,"Invalid phone number format");
//            return false;
        } else {
           
            return true;
        }
    }
               private boolean usernamePatternCorrect(String username) {
                int f=0;
            
        Pattern pattern = Pattern.compile("(?!_).*[A-Za-z0-9._]+@[A-Za-z0-9._]+\\.[A-Za-z]{2,4}");
        Matcher matcher = pattern.matcher(username);
        boolean bool = matcher.matches();
        if (!bool) {
            JOptionPane.showMessageDialog(null,"Special characters are not allowed other than _, @");
            return false;
        } else {
           
          
            return true;
        }
    }
                 boolean checkforunique(){
                     return false;
                 }
    private void btnRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegister1ActionPerformed
        // TODO add your handling code here:
        int f=0;
         String name = txtName.getText();
         //String lastname= txtName1.getText();
        String sex;
        emailAdd = txtEmailId.getText();
        if(radMale.isSelected())
            sex = radMale.getText();
        else 
            sex = radFemale.getText();
        
        String bloodGroup = bloodGroupJComboBox1.getSelectedItem().toString();
        String contactNum = txtContactDonor.getText(); 
        String address = txtAddress.getText();
        String emergencyPOC = txtEmergencyName.getText();
        String emergencyPOC_Num = txtEmergencyContact.getText();
        String sign = txtSignature.getText();
        //int age =Integer.parseInt(txtAge.getText());
        int age=30;
        
        
      
        boolean isOrganAvaiNow = false;
        if(radOrganAvailYes.isSelected())
            isOrganAvaiNow = true;
        else if(radOrganAvailNo.isSelected())
            isOrganAvaiNow = false;
        
        if(isFirstnameValid(name)){
            f++;
        }
        else{
            return;
        }
        if(valage(txtAge.getText())){
            age =Integer.parseInt(txtAge.getText());
            f++;
        }
        else{
            return;
        }
        if(valPhone(contactNum)){
            f++;
        }
        else{
            return;
        }
        if(usernamePatternCorrect(emailAdd)){
            f++;
        }
        else{
        return;
    }if(address.equals("")){
        JOptionPane.showMessageDialog(null, "Address cannot be empty");
        return;
    }
    if(sign.equals("")){
            JOptionPane.showMessageDialog(null, "Sign cannot be empty");
        return;
    }
     if(valPhone(emergencyPOC)){
            f++;
        }
        else{
            return;
        }
      if(isFirstnameValid(emergencyPOC) ){
            f++;
        }
        else{
            return;
        }
            
            
        
        Donor d  = ecosystem.createDonor(name, age, sex,bloodGroup, contactNum, address, sign, emailAdd, emergencyPOC, emergencyPOC_Num, isOrganAvaiNow, organList);
        ecosystem.getDonorDirectory().add(d);
        JOptionPane.showMessageDialog(null,"Thank you for registering with us!!");
         dB4OUtil.storeSystem(ecosystem);
         JOptionPane.showMessageDialog(null, "Thanks for donation");
     
        if(f==0){
            JOptionPane.showConfirmDialog(null, "Please enter the right details");
            
        }
        
      //  ArrayList<String> organDirectory = new ArrayList<String>();
        //String uname = usernameText.getText();
//        if(Heart.isSelected()){
//            SorganDirectory.add("Heart");
//        } 
//        if(Lungs.isSelected()){
//            SorganDirectory.add("Lungs");
//        }
        //Donor donor = new Donor();
        //donorDirectory.createDonor(name, age, sex, address, contactNum, address, sign, emailAdd, emergencyPOC, emergencyPOC_Num, isOrganAvaiNow, organList);
        
        
       
    }//GEN-LAST:event_btnRegister1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bloodGroupJComboBox1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblOrgan1;
    private javax.swing.JComboBox organJComboBox;
    private javax.swing.JRadioButton radFemale;
    private javax.swing.JRadioButton radMale;
    private javax.swing.JRadioButton radOrganAvailNo;
    private javax.swing.JRadioButton radOrganAvailYes;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtContactDonor;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtEmergencyContact;
    private javax.swing.JTextField txtEmergencyName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSignature;
    // End of variables declaration//GEN-END:variables
}
